config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/about', to: 'about#index'
  get '/contact', to: 'contact#index'
  post '/contact', to: 'contact#create', as: 'contact_submit'
  resources :products do
    resources :reviews do
      resources :likes, only: [:create, :destroy]
    end
  end


  # get '/products', to: 'products#index'
  # get '/products/new', to: 'products#new'
  # post '/products/new', to: 'products#new'
  # delete '/questions/:id', to: 'questions#destroy'
  # get '/questions/:id/edit', to: 'questions#edit'
  # get '/questions/:id', to: 'questions#show'
  # post '/questions/:id/comments', to: 'comments#create'
  # get '/faq', to: 'home#faq'
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end


  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :review_id, uniqueness: {scope: :user_id}
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :category
  belongs_to :user
  has_many :reviews

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates(:title, { presence: true, uniqueness: true })
  validates(:description,{ presence: true, length: { minimum: 10 } })
  validates :price,{ presence: true, numericality: true }


  after_initialize :set_defaults
  before_validation :titleize_title

  # def self.search(find)
  #   self.where(["title ILIKE ? OR description ILIKE ?", "%"+find+"%", "%"+find+"%"])
  # end


  # def self.search(find)
  #   results = self.where("title like ?", "%#{find}%")
  #   results.or self.where("description like ?", "%#{find}%")
  #   results
  # end

  def self.search(string)
    where(['title ILIKE ? OR description ILIKE ?', "%#{string}%", "%#{string}%"]).order(['description ILIKE ?', "%#{string}%"], ['title ILIKE ?', "%#{string}%"])
  end

  private

  def titleize_title
    self.title = title.capitalize if title.present?
  end

  def set_defaults
    self.price ||= 1.0
    self.sale_price ||= 1.0
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :body, presence: true

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  def liked_by?(user)
    likes.find_by_user_id(user.id).present?
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :products, through: :taggings

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :product
  belongs_to :tag

  validates :product_id, uniqueness: { scope: :tag_id }
end

app/models/user.rb
class User < ApplicationRecord
  #if you add an attribute accessor to an AR object then you will be able to capture that from the form and have it in memory but it will not be stored in the database if you do'nt have a db field for it
  #attr_accessor :abc  <<- put an :abc field in the form and you'll be able to use it's input


  #this is a built in rails method that helps us with user auth.
  #it will automatically add a presence validator for the password field
  #when given a password it will generate a salt and then it will hash the salt and password combo and will store the result of the Hashing (using bcrypt) along with the randomly generated salt into a database field called 'password_digest'
  #if you skip 'password_confirmation' field then it won't give you a validation error for it. if you provide 'password_confirmation' then it will validate that the password matches the password_confirmation
  #we will get a method called 'authenticate' which will test if the user has entered the correct password or not
  has_secure_password
  has_many :products
  has_many :reviews, dependent: :nullify

  has_many :likes, dependent: :destroy
  has_many :liked_reviews, through: :likes, source: :review

  validates(:first_name, { presence: true })
  validates(:last_name, { presence: true })
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates(:email, { presence: true, uniqueness: { case_sensitive: false }, format: VALID_EMAIL_REGEX })

  before_validation :downcase_email


  def self.search(search_term)
    where(['first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?', "%#{search_term}%", "%#{search_term}%", "%#{search_term}%"])
  end

  def self.created_after(date)
    where(['created_at > ?', "#{date}"])
  end

  def self.is_not(name)
    where('first_name != ? AND last_name != ?', "#{name}", "#{name}")
  end

  def full_name
    "#{first_name} #{last_name}".titleize
  end


  private


  def downcase_email
    self.email.downcase! if email.present?
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
  def create
    @name = params[:name] # you can access this inside the view file
    # render plain: "Thank you #{params[:name]} for contacting us"
    redirect_to contact_path({name: @name})
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    like = Like.new
    review = Review.find params[:review_id]
    like.review = review
    like.user = current_user
    if like.save
      redirect_to product_path(review.product), notice: 'thanks for liking!'
    else
      redirect_to product_path(review.product), alert: 'can\'t like! liked already!'
    end
  end

  def destroy
    review = Review.find params[:review_id]
    like = current_user.likes.find params[:id]
    like.destroy
    redirect_to review_path(review), notice: "like removed!"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    @product.user = current_user

    if @product.save
      ProductMailer.new_product_notify(@product).deliver_now
      redirect_to product_path(@product), notice: 'Product created!'
    else
      flash[:alert] = "uuuuuuuuuuuuuuuuuuuuu"
      render :new
    end
  end

  def show
    @product = Product.find params[:id]
    @review = Review.new
    # render json: params
  end

  def index
    @product = Product.last(50)
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    # product_params = params.require(:product).permit([:title, :description, :price])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    product = Product.find params[:id]
    product.destroy
    redirect_to products_path
  end


  private


  def find_product
    @product = Product.find params[:id]
  end

  def product_params
    params.require(:product).permit([:title, :description, :price, :category_id, { tag_ids: [] }])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "user created!"
      # redirect_to products_path
      redirect_to root_path
    else
      flash[:alert] = "something went wrong!"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name,:last_name,:email,:password,:password_confirmation)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/edit.html.erb
<h1>edit product</h1>

<%= form_for @product do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_area :price %>
  </div>
  <div>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name %>
  </div>
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h1>products listing</h1>
<h3><%= link_to "new product", new_product_path()%></h3>
<hr>

<% @product.each do |product| %>
  <h3><%= link_to product.title, product_path(product) %></h3>
    <p><%= product.user.first_name %></p>
  <hr>
<% end %>

app/views/products/new.html.erb
<h1>new product</h1>

<%= @product.errors.full_messages.join(', ') %>

<%= form_for @product do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_area :price %>
  </div>
  <div>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name %>
  </div>
  <div class="form-group">
    <%= f.collection_select :tag_ids, Tag.order(:name), :id, :name,
      {},
      { multiple: true, class: 'chosen-select', style: 'width: 400px' } %>
  </div>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>

<p><%= @product.description %></p>
<p>uploaded by: <%= @product.user.first_name %></p>

<p>price: $<%= @product.price %></p>

<p>Tags: <%= @product.tags.pluck(:name).join(', ') %></p>

<%#rails enables us to make links and non-GET requests by setting the `method`
    attribute for `link_to`. Rails uses Javascript to accomplish that. %>


<h3><%= link_to 'edit', edit_product_path(@product)%></h3>
<h3><%= link_to 'delete', product_path(@product), method: :delete, data: {confirm:'Are you sure?'} %></h3>

<hr>

<h2>Add a review</h2>
<%= form_for [@product, @review] do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

<% if @review.errors.any? %>
    <hr>
  <ul>
    <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %><li>
    <% end %>
  </ul>
<% end %>


<hr>
<% if @product.reviews != nil %>
  <% @product.reviews.each do |review| %>
      <p><%= review.body %></p>
      <p>Uploaded by <%= review.user.first_name %>  |  <%= review.likes.count %> likes</p>
        <% if user_signed_in? && review.liked_by?(current_user) %>
            <%= link_to "-like", product_review_like_path(@product, review, review.like_for(current_user)), method: :delete %>
        <% else %>
            <%= link_to "+like", product_review_likes_path(@product, review), class: "icon-big", method: :post %>
        <% end %>
        <%= link_to('Delete', product_review_path(@product,review), method: :delete, data: {confirm: 'YYEA'}) %>
      <hr>
  <% end %>
<% end %>